# Generated by Django 4.2.5 on 2023-09-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_user', '0002_alter_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
