# Generated by Django 4.2.5 on 2023-09-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_user', '0003_alter_user_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BorrowedBook',
        ),
    ]
