# Generated by Django 4.2.5 on 2023-09-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src_booktransaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowedbook',
            name='renewed',
        ),
    ]
