# Generated by Django 4.2.5 on 2023-09-09 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_booktransaction', '0002_remove_borrowedbook_renewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
