# Generated by Django 4.2.5 on 2023-09-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src_booktransaction', '0003_borrowedbook_is_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowedbook',
            name='is_renewed',
            field=models.BooleanField(default=False),
        ),
    ]
